services:
  breba-proxy:
    build:
      context: .
    container_name: breba-proxy
    ports:
      - "8000:8000"
    env_file:
      - ./breba-proxy/.env
    environment:
      HOST: breba-proxy
      PORT: 8000
      GOOGLE_APPLICATION_CREDENTIALS: /adc.json # This is needed for accessing Google Cloud
    volumes:
      - ./adc.json:/adc.json:ro  # ← Mount the JSON key read-only